name: perpustakaan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.2
  url_launcher: ^6.0.20
  dynamic_themes: ^1.0.1
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  http: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  mysql1: ^0.20.0
  get: ^4.7.2
  flutter_local_notifications: ^19.1.0
  socket_io_client: ^3.1.1
  connectivity_plus: ^5.0.2
  network_info_plus: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons8-book-96.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/
